import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy - Mere Apne Fincare',
  description: 'Privacy Policy for Mere Apne Small Fincare Nidhi Limited',
};

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-lg shadow-lg p-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-8">
            Privacy Policy - MERE APNE SMALL FINCARE NIDHI LIMITED
          </h1>
          
          <div className="prose prose-lg max-w-none">
            <p className="text-gray-700 mb-6">
              ("we", "our", or "us") is committed to protect your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by MERE APNE SMALL FINCARE NIDHI LIMITED.
            </p>

            <p className="text-gray-700 mb-6">
              This Privacy Policy applies to our website, https://mereapnenidhi.com/, and its associated subdomains (collectively, our "Service") alongside our application, Mere Apne Nidhi Mob App.
            </p>

            <p className="text-gray-700 mb-8">
              By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Definitions and key terms</h2>
            <p className="text-gray-700 mb-4">For this Privacy Policy:</p>
            
            <div className="space-y-4 mb-8">
              <div>
                <strong className="text-gray-900">Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
              </div>
              <div>
                <strong className="text-gray-900">Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to MERE APNE SMALL FINCARE NIDHI LIMITED having office at Raghuwansh Complex Near Azad Garden Chandrapur Chandrapur MH 442401 IN that is responsible for your information under this Privacy Policy.
              </div>
              <div>
                <strong className="text-gray-900">Country:</strong> where Mere Apne Nidhi or the owners/founders of MERE APNE SMALL FINCARE NIDHI LIMITED are based, in this case is India.
              </div>
              <div>
                <strong className="text-gray-900">Customer:</strong> refers to the company, organization or person that signs up to use the MERE APNE SMALL FINCARE NIDHI LIMITED Service to manage the financial/accounting records and provide other related services to their customers/service users.
              </div>
              <div>
                <strong className="text-gray-900">Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Mere Apne Nidhi and use the services.
              </div>
              <div>
                <strong className="text-gray-900">IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
              </div>
              <div>
                <strong className="text-gray-900">Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
              </div>
              <div>
                <strong className="text-gray-900">Service:</strong> refers to the service provided by Mere Apne Nidhi as described in the relative terms (if available) and on this platform.
              </div>
              <div>
                <strong className="text-gray-900">Website:</strong> Mere Apne Nidhi's site, which can be accessed via this URL https://MEREAPNENIDHI.COM/.
              </div>
              <div>
                <strong className="text-gray-900">You:</strong> an entity that is licensed user of Mere Apne Nidhi or their customers/service users.
              </div>
            </div>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">What Information Do We Collect?</h2>
            <p className="text-gray-700 mb-4">We collect information from you when you login to our Website/Mobile App:</p>
            <ul className="list-disc list-inside text-gray-700 mb-6 space-y-2">
              <li>Name /Username</li>
              <li>Phone Numbers</li>
              <li>Email Addresses</li>
              <li>Mailing Addresses</li>
            </ul>
            <p className="text-gray-700 mb-8">
              We also collect information from mobile devices for a better user experience, although these features are completely optional:
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">How Do We Use the Information We Collect?</h2>
            <p className="text-gray-700 mb-4">Any of the information we collect from you may be used in one of the following ways:</p>
            <ul className="list-disc list-inside text-gray-700 mb-8 space-y-2">
              <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
              <li>To improve our service (we continually strive to improve our service offerings based on the information and feedback we receive from you)</li>
              <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
              <li>To process transactions</li>
              <li>To administer a contest, promotion, survey or other site feature</li>
            </ul>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">When do we use customer information from third parties?</h2>
            <p className="text-gray-700 mb-8">
              We receive some information from the third parties when you login to our portal or app. For example, when you submit your email address to us to show interest in becoming our customer, we receive information from a third party that provides automated fraud detection services to us. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Do we share the information we collect with third parties?</h2>
            <p className="text-gray-700 mb-4">
              We may engage trusted third-party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and our service, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through our platform. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.
            </p>
            <p className="text-gray-700 mb-8">
              We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Where and when is information collected from customers and end users?</h2>
            <p className="text-gray-700 mb-8">
              We will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">How Do We Use Your Email Address?</h2>
            <p className="text-gray-700 mb-4">
              By submitting your email address on this both, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Could my information be transferred to other countries?</h2>
            <p className="text-gray-700 mb-8">
              We are incorporated in India. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Is the information collected through our service secure?</h2>
            <p className="text-gray-700 mb-8">
              We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are fool proof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Can I update or correct my information?</h2>
            <p className="text-gray-700 mb-8">
              This can be done by your Company/organisation that is licensed user of NidhExpert or through our portal/app as per the policy of our licensed user.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Sale of Business</h2>
            <p className="text-gray-700 mb-8">
              We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of us or any of its Corporate Affiliates (as defined herein), or that portion of us or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Affiliates</h2>
            <p className="text-gray-700 mb-8">
              We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy,"Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with us, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">How Long Do We Keep Your Information?</h2>
            <p className="text-gray-700 mb-8">
              We keep your information only so long as we need it to provide service to you and fulfil the purposes described in this policy. This is also the case for any one that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we'll either remove it from our systems or depersonalize it so that we can't identify you.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">How Do We Protect Your Information?</h2>
            <p className="text-gray-700 mb-8">
              We implement a variety of security measures to maintain the safety of your personal information when you submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL)technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to us or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Governing Law</h2>
            <p className="text-gray-700 mb-8">
              The laws of India, excluding its conflicts of law rules, shall govern this Agreement and your use of our service. Your use of our service may also be subject to other local, state, national, or international laws.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Your Consent</h2>
            <p className="text-gray-700 mb-8">
              By using our service, registering an account, or making a purchase, you consent to this Privacy Policy.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Links to Other Websites</h2>
            <p className="text-gray-700 mb-8">
              This Privacy Policy applies only to the Services. The Services may contain links toother websites not operated or controlled by Mere Apne Nidhi. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website's own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Cookies</h2>
            <p className="text-gray-700 mb-8">
              We use "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our website. Most web browsers can be set to disable the use of Cookies. However, If you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Advertising</h2>
            <p className="text-gray-700 mb-8">
              Advertising keeps us and many of the websites and services you use free of charge. We work hard to make sure that ads are safe, unobtrusive, and as relevant as possible.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Cookies for Advertising</h2>
            <p className="text-gray-700 mb-8">
              Cookies help to make advertising more effective. Without cookies, it's really hard for an advertiser to reach its audience, or to know how many ads were shown and how many clicks they received.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Remarketing Services</h2>
            <p className="text-gray-700 mb-8">
              We use remarketing services. What Is Remarketing? In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they're "following" people around the internet by serving ads on the websites and platforms they use most.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Payment Details</h2>
            <p className="text-gray-700 mb-8">
              In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Kids' Privacy</h2>
            <p className="text-gray-700 mb-8">
              We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parentor guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Changes To Our Privacy Policy</h2>
            <p className="text-gray-700 mb-8">
              If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Third-Party Services</h2>
            <p className="text-gray-700 mb-8">
              We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").
            </p>
            <p className="text-gray-700 mb-8">
              You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.
            </p>
            <p className="text-gray-700 mb-8">
              Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Tracking Technologies</h2>
            
            <h3 className="text-xl font-semibold text-gray-900 mb-3">Google Maps APIs</h3>
            <p className="text-gray-700 mb-4">
              Google Maps API is a robust tool that can be used to create a custom map, a searchable map, check-in functions, display live data synching with location, plan routes, or create a mashup just to name a few.
            </p>
            <p className="text-gray-700 mb-4">
              Google Maps API may collect information from You and from Your Device for security purposes.
            </p>
            <p className="text-gray-700 mb-6">
              Google Maps API collects information that is held in accordance with its Privacy Policy.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 mb-3">Cookies</h3>
            <p className="text-gray-700 mb-6">
              We use Cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit our service as we would not be able to remember that you had logged in previously.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 mb-3">Local Storage</h3>
            <p className="text-gray-700 mb-6">
              Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information stored in the HTTP request header.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 mb-3">Sessions</h3>
            <p className="text-gray-700 mb-8">
              We use "Sessions" to identify the areas of our website that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">What is personal data?</h2>
            <p className="text-gray-700 mb-4">
              Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person's name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical address, sexual orientation, and ethnicity. The Data Protection Principles include requirements such as:
            </p>
            <ul className="list-disc list-inside text-gray-700 mb-8 space-y-2">
              <li>Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.</li>
              <li>Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.</li>
              <li>Personal data should be held no longer than necessary to fulfil its purpose.</li>
              <li>People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Individual Data Subject's Rights – Data Access, Portability and Deletion</h2>
            <p className="text-gray-700 mb-8">
              We are committed to helping our customers meet the data subject rights requirements of GDPR. We process or store all personal data in fully vetted, DPA compliant vendors. We do store all conversation and personal data for up to 6 year sunless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days.
            </p>
            <p className="text-gray-700 mb-8">
              We are aware that if you are working with EU customers, you need to be able to provide them with the ability to access, update, retrieve and remove personal data. We got you! We've been set up as self-service from the start and have always given you access to your data and your customers data. Our customer support team is here for you to answer any questions you might have about working with the API.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Contact Us</h2>
            <p className="text-gray-700 mb-4">Don't hesitate to contact us if you have any questions.</p>
            <p className="text-gray-700 mb-8">
              Via Email: <a href="mailto:mereapnenidhi@gmail.com" className="text-blue-600 hover:text-blue-800">mereapnenidhi@gmail.com</a>
            </p>

            <div className="mt-8 pt-8 border-t border-gray-200">
              <p className="text-sm text-gray-500">
                A-21 GALI NO. 3, GURU NANAK PURA LAXMI NAGAR DELHI East Delhi DL 110092 IN | Phone: +91-7844884646 | Email: mereapnenidhi@gmail.com
              </p>
              <p className="text-sm text-gray-500 mt-2">
                Copyright © 2025 MERE APNE SMALL FINCARE NIDHI LIMITED
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
